### ISSUE TITLE
Internal DNS resolve - when f5 is setup with public dns

### ISSUE THREAD

**Issue by dagfinnc** [akhmarov/f5_otp#1]
Tried to implement the OTP Register portal first, but had a problem with resolving LDAP FQDN against the customers internal DNS. We have multiple tenants on the F5 and have DNS configured to public DNS servers.

How do I resolve the ldap fqdn (internal domain) in APM-LDAP-Modify-ilx plugin, when the DNS is configured for public DNS ?

**Comment by akhmarov** [comment]
Current implementation assumes that BIG-IP has internal DNS configured that is able to resolve all names. Will try to implement this feature. Currently the simplest way is to add below code into file APM-LDAP-Modify.js on line #143:
```js
dns.setServers([
  '192.168.1.1',
  '192.168.2.1'
]);
```

**Comment by akhmarov** [comment]
Released v1.2.0 with DNS customisation support
