### ISSUE TITLE
Problem connecting to LDAP -  invalid LDAP url (scope)

### ISSUE THREAD

**Issue by dagfinnc** [akhmarov/f5_otp#2]
I'm having problems connecting to LDAP.  Tested with LDAPConfig client and LDP.exe

I get TypeError: Invalid LDAP url

pid[23198] plugin[/Common/LDAP-Modify_plugin.APM-LDAP-Modify_ilx] ldapModifyRec error: TypeError: ldap://192.168.9.15:389 is an invalid LDAP url (scope)

Any idea

**Comment by akhmarov** [comment]
Hello Dagfinn!

Please, try these steps:
1. Use ldapsearch utility with arguments that you pass from APM to iRuleLX from BIG-IP
2. Use script test/test_ldap.js with arguments that you pass from APM to iRuleLX from your workstation

**Comment by inc0gGitHub** [comment]
I am having the same issue:
`plugin[/Common/LDAP-Modify_plugin.APM-LDAP-Modify_ilx] ldapModifyRec error: TypeError: ldap://192.168.x.x:389 is an invalid LDAP url (scope)`

F5 APM ver. 15.1.1 Build 0.0.6

**Comment by akhmarov** [comment]
> I am having the same issue:
> `plugin[/Common/LDAP-Modify_plugin.APM-LDAP-Modify_ilx] ldapModifyRec error: TypeError: ldap://192.168.x.x:389 is an invalid LDAP url (scope)`
> 
> F5 APM ver. 15.1.1 Build 0.0.6

Could please check the following?
1. Other error messages in /var/log/ltm near this error
2. Logs on your domain controller
3. Test simple connection to your DC (see below)

```javascript
var ldap = require('ldapjs');
var client = ldap.createClient({
  url: 'ldap://192.168.x.x:389'
});
```

**Comment by akhmarov** [comment]
Found root cause of this issue - newer version of ldapjs dropped support of deprecated versions of NodeJS

To fix this you could try to reinstall supported version:
cd /var/ilx/workspaces/Common/LDAP-Modify_space/extensions/APM-LDAP-Modify_ilx/
npm uninstall ldapjs
npm install ldapjs@1.0.2 --no-bin-links

And after that reload plugin from workspace
